<?php

declare(strict_types=1);

return [
    'GET health' => 'site/health',
    'GET,POST install' => 'site/install',
    'GET,POST login' => 'site/login',
    'POST logout' => 'site/logout',
    'GET,POST oauth/authorize' => 'oauth-authorize/index',
    'POST oauth/token' => 'oauth-token/index',
    'GET dashboard' => 'site/dashboard',
    'GET search' => 'search/index',
    'GET,POST import' => 'import/document',
    'GET favorites' => 'library/favorites',
    'GET archive' => 'library/archive',
    'GET trash' => 'library/trash',
    'POST documents/<id:[0-9a-fA-F-]{36}>/favorite' => 'library/toggle-favorite',
    'POST documents/<id:[0-9a-fA-F-]{36}>/trash' => 'library/trash-document',
    'POST documents/<id:[0-9a-fA-F-]{36}>/restore' => 'library/restore',
    'POST documents/<id:[0-9a-fA-F-]{36}>/delete-forever' => 'library/delete-forever',
    'GET mention/users' => 'mention/users',
    'GET notifications' => 'notification/index',
    'POST notifications/read-all' => 'notification/read-all',
    'POST notifications/<id:[0-9a-fA-F-]{36}>/read' => 'notification/read',
    'POST notifications/<id:[0-9a-fA-F-]{36}>/archive' => 'notification/archive',
    'GET settings/api-keys' => 'api-key/index',
    'POST settings/api-keys/create' => 'api-key/create',
    'POST settings/api-keys/<id:[0-9a-fA-F-]{36}>/revoke' => 'api-key/revoke',
    'GET s/<token:[0-9a-f]{64}>' => 'public/share',
    'GET attachments/<id:[0-9a-fA-F-]{36}>' => 'attachment/download',
    'POST attachments/<id:[0-9a-fA-F-]{36}>/delete' => 'attachment/delete',

    'GET schedule' => 'schedule/index',
    'GET schedule/<view:(?:week|month)>' => 'schedule/index',
    'GET,POST schedule/shift' => 'schedule/shift',
    'POST schedule/shifts/<id:[0-9a-fA-F-]{36}>/delete' => 'schedule/delete-shift',
    'GET,POST schedule/absence' => 'schedule/absence',
    'GET,POST schedule/adjustment' => 'schedule/adjustment',

    'GET vacations' => 'vacation/index',
    'GET,POST vacations/create' => 'vacation/create',
    'GET,POST vacations/allowance' => 'vacation/allowance',
    'POST vacations/<id:[0-9a-fA-F-]{36}>/cancel' => 'vacation/cancel',
    'POST vacations/calendar/sync' => 'vacation/sync-calendar',

    'GET duties' => 'duty/index',
    'GET duties/<id:[0-9a-fA-F-]{36}>' => 'duty/view',
    'GET,POST duties/create' => 'duty/create',
    'POST duties/<id:[0-9a-fA-F-]{36}>/participants' => 'duty/add-participant',
    'POST duties/<id:[0-9a-fA-F-]{36}>/participants/<participantId:[0-9a-fA-F-]{36}>/delete' => 'duty/remove-participant',
    'POST duties/<id:[0-9a-fA-F-]{36}>/generate' => 'duty/generate',
    'POST duties/<id:[0-9a-fA-F-]{36}>/swap' => 'duty/swap',
    'POST duties/<id:[0-9a-fA-F-]{36}>/delete' => 'duty/delete',

    'GET collections' => 'collection/index',
    'GET,POST collections/create' => 'collection/create',
    'GET collections/<id:[0-9a-fA-F-]{36}>' => 'collection/view',
    'GET,POST collections/<id:[0-9a-fA-F-]{36}>/edit' => 'collection/update',
    'POST collections/<id:[0-9a-fA-F-]{36}>/archive' => 'collection/archive',
    'GET collections/<id:[0-9a-fA-F-]{36}>/access' => 'access/collection',
    'POST collections/<id:[0-9a-fA-F-]{36}>/access/grant' => 'access/grant-collection',
    'POST collections/<id:[0-9a-fA-F-]{36}>/access/<permissionId:[0-9a-fA-F-]{36}>/delete' => 'access/revoke-collection',

    'GET templates' => 'template/index',
    'GET,POST templates/create' => 'template/create',
    'GET templates/<id:[0-9a-fA-F-]{36}>' => 'template/view',
    'GET,POST templates/<id:[0-9a-fA-F-]{36}>/edit' => 'template/update',
    'GET,POST templates/<id:[0-9a-fA-F-]{36}>/use' => 'template/use',
    'POST templates/<id:[0-9a-fA-F-]{36}>/delete' => 'template/delete',

    'GET,POST documents/create' => 'document/create',
    'GET documents/<id:[0-9a-fA-F-]{36}>' => 'document/view',
    'GET documents/<id:[0-9a-fA-F-]{36}>/export/<format:(?:md|markdown|html|json)>' => 'export/document',
    'GET,POST documents/<id:[0-9a-fA-F-]{36}>/edit' => 'document/update',
    'POST documents/<id:[0-9a-fA-F-]{36}>/archive' => 'document/archive',
    'POST documents/<documentId:[0-9a-fA-F-]{36}>/attachments' => 'attachment/upload',
    'GET documents/<documentId:[0-9a-fA-F-]{36}>/history' => 'revision/index',
    'GET revisions/<id:[0-9a-fA-F-]{36}>' => 'revision/view',
    'POST revisions/<id:[0-9a-fA-F-]{36}>/restore' => 'revision/restore',
    'GET documents/<documentId:[0-9a-fA-F-]{36}>/share' => 'share/manage',
    'POST documents/<documentId:[0-9a-fA-F-]{36}>/share' => 'share/save',
    'POST shares/<id:[0-9a-fA-F-]{36}>/revoke' => 'share/revoke',
    'GET documents/<id:[0-9a-fA-F-]{36}>/access' => 'access/document',
    'POST documents/<id:[0-9a-fA-F-]{36}>/access/grant' => 'access/grant-document',
    'POST documents/<id:[0-9a-fA-F-]{36}>/access/<permissionId:[0-9a-fA-F-]{36}>/delete' => 'access/revoke-document',
    'POST documents/<documentId:[0-9a-fA-F-]{36}>/comments' => 'comment/create',
    'POST documents/<documentId:[0-9a-fA-F-]{36}>/comments/<parentId:[0-9a-fA-F-]{36}>/reply' => 'comment/create',
    'POST comments/<id:[0-9a-fA-F-]{36}>/update' => 'comment/update',
    'POST comments/<id:[0-9a-fA-F-]{36}>/resolve' => 'comment/resolve',
    'POST comments/<id:[0-9a-fA-F-]{36}>/delete' => 'comment/delete',

    'GET admin/users' => 'user/index',
    'GET,POST admin/users/create' => 'user/create',
    'GET,POST admin/users/<id:[0-9a-fA-F-]{36}>' => 'user/update',
    'GET admin/audit' => 'audit/index',

    'GET admin/groups' => 'group/index',
    'GET,POST admin/groups/create' => 'group/create',
    'GET admin/groups/<id:[0-9a-fA-F-]{36}>' => 'group/view',
    'GET,POST admin/groups/<id:[0-9a-fA-F-]{36}>/edit' => 'group/update',
    'POST admin/groups/<id:[0-9a-fA-F-]{36}>/delete' => 'group/delete',
    'POST admin/groups/<id:[0-9a-fA-F-]{36}>/members' => 'group/add-member',
    'POST admin/groups/<id:[0-9a-fA-F-]{36}>/members/<userId:[0-9a-fA-F-]{36}>/delete' => 'group/remove-member',

    'GET admin/webhooks' => 'webhook/index',
    'GET,POST admin/webhooks/create' => 'webhook/create',
    'GET admin/webhooks/<id:[0-9a-fA-F-]{36}>' => 'webhook/view',
    'GET,POST admin/webhooks/<id:[0-9a-fA-F-]{36}>/edit' => 'webhook/create',
    'POST admin/webhooks/<id:[0-9a-fA-F-]{36}>/rotate' => 'webhook/rotate',
    'POST admin/webhooks/<id:[0-9a-fA-F-]{36}>/test' => 'webhook/test',
    'POST admin/webhooks/<id:[0-9a-fA-F-]{36}>/delete' => 'webhook/delete',

    'GET admin/oauth-apps' => 'oauth-app/index',
    'GET,POST admin/oauth-apps/create' => 'oauth-app/create',
    'GET admin/oauth-apps/<id:[0-9a-fA-F-]{36}>' => 'oauth-app/view',
    'GET,POST admin/oauth-apps/<id:[0-9a-fA-F-]{36}>/edit' => 'oauth-app/create',
    'POST admin/oauth-apps/<id:[0-9a-fA-F-]{36}>/rotate' => 'oauth-app/rotate',
    'POST admin/oauth-apps/<id:[0-9a-fA-F-]{36}>/revoke-tokens' => 'oauth-app/revoke-tokens',
    'POST admin/oauth-apps/<id:[0-9a-fA-F-]{36}>/delete' => 'oauth-app/delete',

    'POST api/<method:[A-Za-z0-9._-]+>' => 'api/dispatch',
    'OPTIONS api/<method:[A-Za-z0-9._-]+>' => 'api/options',
];